name: Publish Python package

on:
  push:
    tags:
      - v.*

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        cibw_python: [ "cp310-*", "cp311-*" ]
    defaults:
      run:
        shell: bash
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
    steps:
      - uses: actions/checkout@v3
      - run: |
          GOBIN=$(PWD) go install golang.org/x/tools/cmd/goimports@latest
          GOBIN=$(PWD) go install golang.org/x/tools/cmd/gopy@latest
          export PATH="$(PWD):$PATH"
          gopy pkg -author "Athenian" -desc "Python bindings to ghid, decoding and encoding utilities for GitHub GraphQL Node IDs" -email "denys@athenian.co" -output python -url "https://github.com/athenianco/ghid" -vm python3 -version ${GITHUB_REF_NAME#v} github.com/athenianco/ghid
      - uses: pypa/cibuildwheel@v2.11.2
        package-dir: python
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: ${{ matrix.cibw_python }}
          CIBW_ARCHS: auto64
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: wheelhouse/*.whl
  publish:
    needs: [ build-wheels ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/
      - run: ls -al dist/
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}